[colors.bright]
black = "#494d64"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#c6a0f6"
red = "#ed8796"
white = "#b7bdf8"
yellow = "#eed49f"

[colors.cursor]
cursor = "#cad3f5"
text = "#24273a"

[colors.normal]
black = "#24273a"
blue = "#8aadf4"
cyan = "#8bd5ca"
green = "#a6da95"
magenta = "#c6a0f6"
red = "#ed8796"
white = "#cad3f5"
yellow = "#eed49f"

[colors.primary]
background = "#24273a"
bright_foreground = "#b7bdf8"
foreground = "#cad3f5"

[colors.selection]
background = "#363a4f"
text = "#cad3f5"

[font]
size = 12

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "cd $(/nix/store/pb0dzfpd78p5gwrx9ysifsxf223dsgii-fd-10.3.0/bin/fd . /mnt/work /mnt/work/dev/ /run /run/current-system ~/.local/ ~/ --max-depth 2 | fzf)\r"
key = "F"
mods = "Control"

[[keyboard.bindings]]
action = "Paste"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[terminal.shell]
program = "/nix/store/vl5ml2v2ffgyr90k13x8k4dl98d12bi2-fish-4.1.2/bin/fish"

[window]
decorations = "full"
dynamic_padding = true
opacity = 1.0
startup_mode = "Maximized"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 100
lines = 30

[window.padding]
x = 10
y = 10
